# Lethe — Quickstart

**Link Inference Attacks for Evaluation of Edge Unlearning Methods**

This notebook does two things:

1. Runs a real Lethe benchmark configuration end-to-end (DBLP × GCN × high-centrality
   forget set) and reproduces the shape of Table 2 from the paper.
2. Shows you how to drop **your own unlearning method** into that same benchmark
   and have it scored against the published baselines.

It assumes the `lethe` environment is already active (see the README) and that this
notebook is being run from inside a clone of the repository.

> The demo config evaluates 3 unlearners (Original, Gold Model, Fine-tuning) instead of
> the 16 in the full benchmark.

## 0. Locate the repository

Configs resolve paths such as `resources/data` and `configs/snippets/` relative to the
repository root, so the working directory is moved there for the rest of the notebook.

In [1]:
import os
from pathlib import Path

root = Path.cwd()
while not (root / "main.py").exists() and root != root.parent:
    root = root.parent

assert (root / "lethe").is_dir(), "Run this notebook from inside the Lethe repository."
os.chdir(root)

import torch
print("Repository root:", root)
print("torch:", torch.__version__, "| CUDA:", torch.cuda.is_available())

Repository root: /path/to/Lethe
torch: 2.13.0 | CUDA: False

## 1. Run the benchmark

`main.py` takes a single JSONC config that fully specifies the experiment: dataset,
forget-set construction, model, unlearners, and metrics.

The first run downloads DBLP (~15 MB) and trains the Original and Gold models. Both are
cached under `resources/cached/` by the config's `alias`, so every later run reuses them.

`SaveValues` *appends* to its output file, so `run_lethe` deletes any previous results
first — otherwise repeated runs accumulate duplicate records.

In [2]:
import subprocess, sys

CONFIG  = "configs/demo/DBLP_GCN_demo.jsonc"
RESULTS = "output/runs/demo/DBLP_GCN_demo.json"

def run_lethe(config, results_path):
    if os.path.exists(results_path):
        os.remove(results_path)

    proc = subprocess.Popen([sys.executable, "main.py", config],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            text=True, bufsize=1)
    for line in proc.stdout:
        print(line, end="")
    proc.wait()
    if proc.returncode != 0:
        raise RuntimeError(f"Run failed with exit code {proc.returncode}")
    return results_path

run_lethe(CONFIG, RESULTS)
print("\nResults written to:", RESULTS)

2026-09-29 14:08:53 | INFO | 35090 - Creating Global Context for: configs/demo/DBLP_GCN_demo.jsonc
2026-09-29 14:08:53 | INFO | 35090 - Setting seeds to: 0
2026-09-29 14:08:53 | INFO | 35090 - REMOVAL TYPE SET AS edge
2026-09-29 14:08:53 | INFO | 35090 - Caching System: True.
2026-09-29 14:08:53 | INFO | 35090 - Instantiating: torch_geometric.datasets.CitationFull
{'root': 'resources/data', 'name': 'DBLP'}
2026-09-29 14:08:53 | INFO | 35090 - Created Configurable: lethe.data.data_sources.TorchGeometricDataSource.TorchGeometricDataSource
2026-09-29 14:08:53 | INFO | 35090 - {'class': 'lethe.data.data_sources.TorchGeometricDataSource.TorchGeometricDataSource', 'parameters': {'datasource': {'class': 'torch_geometric.datasets.CitationFull', 'parameters': {'root': 'resources/data', 'name': 'DBLP'}, 'preprocess': []}}}
2026-09-29 14:08:53 | INFO | 35090 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:08:53 | INFO | 35090 - ['all', 'all_shuffled', '-']
2026-09-29 14:08:53 | INFO | 35090 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:08:53 | INFO | 35090 - ['all', 'all_shuffled', '-', 'train_0', 'test']
2026-09-29 14:08:53 | INFO | 35090 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:08:53 | INFO | 35090 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train']
2026-09-29 14:08:53 | INFO | 35090 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterEdgeDifficulty
/path/to/Lethe/lethe/data/datasets/DataSplitterGraph.py:477: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /Users/runner/work/pytorch/pytorch/aten/src/ATen/Context.cpp:823.)
  A_hat = torch.sparse_coo_tensor(edge_index_tilde, weights, (N, N)).coalesce()

2026-09-29 14:08:53 | INFO | 35090 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train', 'forget', 'retain']
2026-09-29 14:08:53 | INFO | 35090 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train', 'forget', 'retain']
2026-09-29 14:08:53 | INFO | 35090 - Created Configurable: lethe.data.datasets.DatasetManager.DatasetManager

2026-09-29 14:08:56 | INFO | 35090 - Loaded Instance from: resources/cached/DBLP_GCN_demo
2026-09-29 14:08:56 | INFO | 35090 - Created Configurable: lethe.model.TorchGraphModel.TorchGraphModel
2026-09-29 14:08:56 | INFO | 35090 - Global Predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x10c93df70>

2026-09-29 14:08:56 | INFO | 35090 - Created Configurable: lethe.unlearners.composite.Identity

2026-09-29 14:08:57 | INFO | 35090 - Created Configurable: lethe.unlearners.GoldModel.GoldModelGraph

2026-09-29 14:08:58 | INFO | 35090 - Instantiating: torch.optim.Adam
/path/to/Lethe/lethe/unlearners/graph_unlearners/GraphUnlearner.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.labels = torch.tensor(self.labels)
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.unlearners.graph_unlearners.Finetuning.Finetuning

2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.running.RunTime
2026-09-29 14:08:58 | INFO | 35090 - Function: <function accuracy_score at 0x158a40220>
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:08:58 | INFO | 35090 - Function: <function accuracy_score at 0x158a40220>
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:08:58 | INFO | 35090 - Function: <function accuracy_score at 0x158a40220>
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.LinkTeller.LinkTeller.LinkTeller
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.link_stealing_attack.link_stealing_attack_0.LinkStealing0
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.measures.SaveValues
2026-09-29 14:08:58 | INFO | 35090 - Created Configurable: lethe.evaluations.manager.Evaluator
2026-09-29 14:08:58 | INFO | 35090 - ####		 Evaluating Unlearner Identity 		####

2026-09-29 14:08:58 | INFO | 35090 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x158a870e0>

2026-09-29 14:08:59 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8250564334085779 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17c0aaf30>
2026-09-29 14:08:59 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.811346276257161 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17c0aaf30>
2026-09-29 14:08:59 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17c0aaff0>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(12623, 13781), (1326, 8484), (15922, 16753), (9938, 13268), (11732, 15617)]
2026-09-29 14:08:59 | INFO | 35090 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0055, std=0.0157, min=0.0000, max=0.1193
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0008, min=0.0000, max=0.0055
[ROC Thresholds] Sample thresholds: [       inf 0.11925697 0.01350016 0.01339448 0.00572484]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.124 0.128 0.174]
auc = 0.415436
2026-09-29 14:09:05 | INFO | 35090 - LinkTeller unlearn auc with sampler balanced: 0.415436

Attack 0 target posterior similarity
2026-09-29 14:09:06 | INFO | 35090 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8700929280372373

Attack 0 target posterior similarity
2026-09-29 14:09:06 | INFO | 35090 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7327601387882576
2026-09-29 14:09:06 | INFO | 35090 - ####		 Evaluating Unlearner GoldModelGraph 		####
2026-09-29 14:09:06 | INFO | 35090 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a420650>
Hello, i am unlearning gm at time  time.struct_time(tm_year=2026, tm_mon=9, tm_mday=29, tm_hour=14, tm_min=9, tm_sec=6, tm_wday=1, tm_yday=272, tm_isdst=1)
2026-09-29 14:09:06 | INFO | 35090 - Instantiating: lethe.model.graphs.GCN.GCN
2026-09-29 14:09:06 | INFO | 35090 - [DBG] model cfg: epochs=100 | hidden=[64] | out=?
2026-09-29 14:09:06 | INFO | 35090 - Instantiating: torch.optim.Adam
2026-09-29 14:09:06 | INFO | 35090 - Instantiating: torch.nn.CrossEntropyLoss
2026-09-29 14:09:06 | INFO | 35090 - [DBG] graph: nodes=17716, edges=100448 | train_len=12755 | test_len=3544 | training_set='retain'
2026-09-29 14:09:06 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:06 | INFO | 35090 - epoch = 0 ---> train_loss = 1.3984	 val_loss = 1.3869	 train_acc = 0.1643
2026-09-29 14:09:06 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:06 | INFO | 35090 - epoch = 1 ---> train_loss = 1.3861	 val_loss = 1.3758	 train_acc = 0.2457
2026-09-29 14:09:06 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 2 ---> train_loss = 1.3752	 val_loss = 1.3649	 train_acc = 0.3476
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:07 | INFO | 35090 - epoch = 3 ---> train_loss = 1.3635	 val_loss = 1.3542	 train_acc = 0.4663
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 4 ---> train_loss = 1.3514	 val_loss = 1.3437	 train_acc = 0.5598
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 5 ---> train_loss = 1.3421	 val_loss = 1.3332	 train_acc = 0.6146
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 6 ---> train_loss = 1.3307	 val_loss = 1.3228	 train_acc = 0.6459
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 7 ---> train_loss = 1.3194	 val_loss = 1.3123	 train_acc = 0.6714
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 8 ---> train_loss = 1.3088	 val_loss = 1.3018	 train_acc = 0.6828
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 9 ---> train_loss = 1.2983	 val_loss = 1.2911	 train_acc = 0.6953
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 10 ---> train_loss = 1.2863	 val_loss = 1.2804	 train_acc = 0.6971
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 11 ---> train_loss = 1.2756	 val_loss = 1.2695	 train_acc = 0.7038
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 12 ---> train_loss = 1.2648	 val_loss = 1.2586	 train_acc = 0.7086
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:07 | INFO | 35090 - epoch = 13 ---> train_loss = 1.2537	 val_loss = 1.2475	 train_acc = 0.7141
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 14 ---> train_loss = 1.2420	 val_loss = 1.2363	 train_acc = 0.7167
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 15 ---> train_loss = 1.2306	 val_loss = 1.2251	 train_acc = 0.7189
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 16 ---> train_loss = 1.2183	 val_loss = 1.2138	 train_acc = 0.7207
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 17 ---> train_loss = 1.2068	 val_loss = 1.2024	 train_acc = 0.7192
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 18 ---> train_loss = 1.1956	 val_loss = 1.1910	 train_acc = 0.7232
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 19 ---> train_loss = 1.1835	 val_loss = 1.1795	 train_acc = 0.7229
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 20 ---> train_loss = 1.1706	 val_loss = 1.1680	 train_acc = 0.7296
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 21 ---> train_loss = 1.1601	 val_loss = 1.1566	 train_acc = 0.7253
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 22 ---> train_loss = 1.1471	 val_loss = 1.1451	 train_acc = 0.7252
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:07 | INFO | 35090 - epoch = 23 ---> train_loss = 1.1358	 val_loss = 1.1337	 train_acc = 0.7305
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 24 ---> train_loss = 1.1245	 val_loss = 1.1223	 train_acc = 0.7301
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 25 ---> train_loss = 1.1107	 val_loss = 1.1109	 train_acc = 0.7344
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 26 ---> train_loss = 1.1008	 val_loss = 1.0996	 train_acc = 0.7327
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 27 ---> train_loss = 1.0893	 val_loss = 1.0884	 train_acc = 0.7354
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 28 ---> train_loss = 1.0766	 val_loss = 1.0772	 train_acc = 0.7366
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 29 ---> train_loss = 1.0651	 val_loss = 1.0661	 train_acc = 0.7399
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 30 ---> train_loss = 1.0516	 val_loss = 1.0551	 train_acc = 0.7433
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 31 ---> train_loss = 1.0418	 val_loss = 1.0441	 train_acc = 0.7433
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 32 ---> train_loss = 1.0314	 val_loss = 1.0333	 train_acc = 0.7460
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:07 | INFO | 35090 - epoch = 33 ---> train_loss = 1.0187	 val_loss = 1.0226	 train_acc = 0.7485
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 34 ---> train_loss = 1.0086	 val_loss = 1.0119	 train_acc = 0.7521
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 35 ---> train_loss = 0.9956	 val_loss = 1.0014	 train_acc = 0.7541
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 36 ---> train_loss = 0.9871	 val_loss = 0.9910	 train_acc = 0.7533
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 37 ---> train_loss = 0.9759	 val_loss = 0.9808	 train_acc = 0.7585
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 38 ---> train_loss = 0.9647	 val_loss = 0.9706	 train_acc = 0.7598
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 39 ---> train_loss = 0.9542	 val_loss = 0.9606	 train_acc = 0.7615
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 40 ---> train_loss = 0.9434	 val_loss = 0.9507	 train_acc = 0.7643
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 41 ---> train_loss = 0.9343	 val_loss = 0.9410	 train_acc = 0.7628
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 42 ---> train_loss = 0.9230	 val_loss = 0.9314	 train_acc = 0.7651
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:07 | INFO | 35090 - epoch = 43 ---> train_loss = 0.9143	 val_loss = 0.9220	 train_acc = 0.7686
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 44 ---> train_loss = 0.9034	 val_loss = 0.9128	 train_acc = 0.7707
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 45 ---> train_loss = 0.8934	 val_loss = 0.9037	 train_acc = 0.7761
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 46 ---> train_loss = 0.8865	 val_loss = 0.8947	 train_acc = 0.7762
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 47 ---> train_loss = 0.8762	 val_loss = 0.8859	 train_acc = 0.7773
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 48 ---> train_loss = 0.8675	 val_loss = 0.8773	 train_acc = 0.7783
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 49 ---> train_loss = 0.8562	 val_loss = 0.8688	 train_acc = 0.7816
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:07 | INFO | 35090 - epoch = 50 ---> train_loss = 0.8492	 val_loss = 0.8605	 train_acc = 0.7825
2026-09-29 14:09:07 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 51 ---> train_loss = 0.8403	 val_loss = 0.8523	 train_acc = 0.7827
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 52 ---> train_loss = 0.8303	 val_loss = 0.8443	 train_acc = 0.7889
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:08 | INFO | 35090 - epoch = 53 ---> train_loss = 0.8237	 val_loss = 0.8365	 train_acc = 0.7904
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 54 ---> train_loss = 0.8157	 val_loss = 0.8288	 train_acc = 0.7905
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 55 ---> train_loss = 0.8056	 val_loss = 0.8212	 train_acc = 0.7867
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 56 ---> train_loss = 0.8005	 val_loss = 0.8139	 train_acc = 0.7921
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 57 ---> train_loss = 0.7938	 val_loss = 0.8066	 train_acc = 0.7931
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 58 ---> train_loss = 0.7835	 val_loss = 0.7996	 train_acc = 0.7964
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 59 ---> train_loss = 0.7782	 val_loss = 0.7926	 train_acc = 0.7945
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 60 ---> train_loss = 0.7674	 val_loss = 0.7858	 train_acc = 0.7973
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 61 ---> train_loss = 0.7640	 val_loss = 0.7792	 train_acc = 0.7989
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 62 ---> train_loss = 0.7582	 val_loss = 0.7727	 train_acc = 0.7999
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:08 | INFO | 35090 - epoch = 63 ---> train_loss = 0.7488	 val_loss = 0.7663	 train_acc = 0.8002
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 64 ---> train_loss = 0.7420	 val_loss = 0.7601	 train_acc = 0.8045
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 65 ---> train_loss = 0.7362	 val_loss = 0.7540	 train_acc = 0.8058
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 66 ---> train_loss = 0.7285	 val_loss = 0.7481	 train_acc = 0.8078
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 67 ---> train_loss = 0.7235	 val_loss = 0.7423	 train_acc = 0.8089
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 68 ---> train_loss = 0.7174	 val_loss = 0.7366	 train_acc = 0.8100
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 69 ---> train_loss = 0.7113	 val_loss = 0.7310	 train_acc = 0.8099
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 70 ---> train_loss = 0.7052	 val_loss = 0.7256	 train_acc = 0.8134
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 71 ---> train_loss = 0.6989	 val_loss = 0.7203	 train_acc = 0.8122
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 72 ---> train_loss = 0.6935	 val_loss = 0.7151	 train_acc = 0.8139
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:08 | INFO | 35090 - epoch = 73 ---> train_loss = 0.6873	 val_loss = 0.7101	 train_acc = 0.8170
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 74 ---> train_loss = 0.6846	 val_loss = 0.7051	 train_acc = 0.8137
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 75 ---> train_loss = 0.6787	 val_loss = 0.7003	 train_acc = 0.8168
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 76 ---> train_loss = 0.6717	 val_loss = 0.6956	 train_acc = 0.8189
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 77 ---> train_loss = 0.6705	 val_loss = 0.6910	 train_acc = 0.8204
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 78 ---> train_loss = 0.6638	 val_loss = 0.6865	 train_acc = 0.8183
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 79 ---> train_loss = 0.6591	 val_loss = 0.6821	 train_acc = 0.8217
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 80 ---> train_loss = 0.6553	 val_loss = 0.6778	 train_acc = 0.8229
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 81 ---> train_loss = 0.6481	 val_loss = 0.6736	 train_acc = 0.8240
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 82 ---> train_loss = 0.6465	 val_loss = 0.6694	 train_acc = 0.8245
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:08 | INFO | 35090 - epoch = 83 ---> train_loss = 0.6428	 val_loss = 0.6654	 train_acc = 0.8247
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 84 ---> train_loss = 0.6355	 val_loss = 0.6615	 train_acc = 0.8289
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 85 ---> train_loss = 0.6299	 val_loss = 0.6577	 train_acc = 0.8300
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 86 ---> train_loss = 0.6278	 val_loss = 0.6539	 train_acc = 0.8307
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 87 ---> train_loss = 0.6250	 val_loss = 0.6503	 train_acc = 0.8286
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 88 ---> train_loss = 0.6207	 val_loss = 0.6467	 train_acc = 0.8319
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 89 ---> train_loss = 0.6173	 val_loss = 0.6432	 train_acc = 0.8300
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 90 ---> train_loss = 0.6161	 val_loss = 0.6398	 train_acc = 0.8343
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 91 ---> train_loss = 0.6125	 val_loss = 0.6365	 train_acc = 0.8310
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 92 ---> train_loss = 0.6080	 val_loss = 0.6333	 train_acc = 0.8318
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:08 | INFO | 35090 - epoch = 93 ---> train_loss = 0.6031	 val_loss = 0.6301	 train_acc = 0.8315
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 94 ---> train_loss = 0.5984	 val_loss = 0.6270	 train_acc = 0.8350
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 95 ---> train_loss = 0.5949	 val_loss = 0.6240	 train_acc = 0.8350
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 96 ---> train_loss = 0.5912	 val_loss = 0.6210	 train_acc = 0.8382
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 97 ---> train_loss = 0.5896	 val_loss = 0.6181	 train_acc = 0.8372
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 98 ---> train_loss = 0.5857	 val_loss = 0.6153	 train_acc = 0.8389
2026-09-29 14:09:08 | INFO | 35090 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:08 | INFO | 35090 - epoch = 99 ---> train_loss = 0.5848	 val_loss = 0.6125	 train_acc = 0.8373
2026-09-29 14:09:08 | INFO | 35090 - TorchGraphModel trained on mps in: 2.098501682281494 secs
2026-09-29 14:09:08 | INFO | 35090 - Created Configurable: lethe.model.TorchGraphModel.TorchGraphModel

Done at  time.struct_time(tm_year=2026, tm_mon=9, tm_mday=29, tm_hour=14, tm_min=9, tm_sec=8, tm_wday=1, tm_yday=272, tm_isdst=1)
2026-09-29 14:09:10 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8259029345372461 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a27efc0>
2026-09-29 14:09:10 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.8150063653723743 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a27efc0>
2026-09-29 14:09:10 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17c0e3260>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(6805, 15687), (5830, 8065), (5220, 12561), (13618, 17432), (15091, 17401)]
2026-09-29 14:09:10 | INFO | 35090 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0049, std=0.0171, min=0.0000, max=0.1952
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0008, min=0.0000, max=0.0055
[ROC Thresholds] Sample thresholds: [       inf 0.195177   0.01018525 0.00931054 0.00559141]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.11  0.114 0.128]
auc = 0.38649
2026-09-29 14:09:16 | INFO | 35090 - LinkTeller unlearn auc with sampler balanced: 0.38649

Attack 0 target posterior similarity
2026-09-29 14:09:17 | INFO | 35090 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8707114362537792

Attack 0 target posterior similarity
2026-09-29 14:09:17 | INFO | 35090 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7343838786672368
2026-09-29 14:09:17 | INFO | 35090 - ####		 Evaluating Unlearner Finetuning 		####
2026-09-29 14:09:17 | INFO | 35090 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a423920>
2026-09-29 14:09:17 | INFO | 35090 - Starting Finetuning with 1 epochs
2026-09-29 14:09:17 | INFO | 35090 - Finetuning - epoch = 0 ---> var_loss = 0.6255

2026-09-29 14:09:18 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8253386004514672 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a2d1460>
2026-09-29 14:09:18 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.8128580521960534 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x17a2d1460>
2026-09-29 14:09:18 | INFO | 35090 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x12f7483e0>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(6805, 15687), (5830, 8065), (5220, 12561), (13618, 17432), (15091, 17401)]
2026-09-29 14:09:18 | INFO | 35090 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0049, std=0.0170, min=0.0000, max=0.1980
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0008, min=0.0000, max=0.0060
[ROC Thresholds] Sample thresholds: [       inf 0.19796729 0.013328   0.01244581 0.00602715]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.1   0.104 0.122]
auc = 0.41197799999999996
2026-09-29 14:09:24 | INFO | 35090 - LinkTeller unlearn auc with sampler balanced: 0.41197799999999996

Attack 0 target posterior similarity
2026-09-29 14:09:25 | INFO | 35090 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8709738428955316

Attack 0 target posterior similarity
2026-09-29 14:09:25 | INFO | 35090 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7335295584212659

Results written to: output/runs/demo/DBLP_GCN_demo.json

## 2. Read the results

Each unlearner contributes one record. The file holds *concatenated* JSON objects
(`{...},{...},`) rather than a single array, so it is wrapped into a list before parsing.

Metric keys are verbose (`sklearn.metrics.accuracy_score.test.unlearned.on_graph:True`)
and the attack keys vary with the config's `target`, so columns are matched by substring
rather than by exact name.

In [3]:
import json
import pandas as pd

def load_results(path):
    raw = open(path).read().strip().rstrip(",")
    return pd.DataFrame(json.loads("[" + raw + "]"))

def summarise(df):
    def col(*needles, default=None):
        for c in df.columns:
            if all(n.lower() in c.lower() for n in needles):
                return df[c]
        return default

    out = pd.DataFrame({
        "Method":      df["unlearner"],
        "RunTime":     col("RunTime"),
        "Acc":         col("accuracy_score", "test", "unlearned"),
        "Acc(forget)": col("accuracy_score", "forget", "unlearned"),
        "LT AUC":      col("LinkTeller", "unlearn"),
        "LS AUC":      col("Link Stealing", "forget/non_exist"),
    })
    return out.round(4)

summarise(load_results(RESULTS))

           Method  RunTime     Acc  Acc(forget)  LT AUC  LS AUC
0        Identity   0.3403  0.8251       0.8113  0.4154  0.7328
1  GoldModelGraph   3.2211  0.8259       0.8150  0.3865  0.7344
2      Finetuning   0.3602  0.8253       0.8129  0.4120  0.7335

**How to read this.** `Acc` barely moves across methods. That is the paper's central
negative result: accuracy cannot distinguish unlearning methods. The attack columns are
the informative ones, and **0.5 is the ideal value** (the adversary is guessing). An AUC
well above 0.5 means the forgotten edges are still recoverable from the model.

The Gold Model row is the reference: it is what genuine retraining achieves.

## 3. Add your own method

An unlearner subclasses `GraphUnlearner` and implements `__unlearn__`. The base class
hands you:

| Attribute | What it is |
|---|---|
| `self.predictor` | the trained model to modify (`.model`, `.optimizer`) |
| `self.dataset.partitions[...]` | the dataset splits (see the note below) |
| `self.task_loss(node_subset=...)` | the predictor's training loss on a subset |
| `self.infected_nodes(edges, hops)` | nodes a GNN of this depth can see the removed edges through |
| `self.hops` | receptive-field depth of the predictor |

Return the modified predictor. Nothing needs to be registered: the factory imports your
class by dotted path (`lethe/core/factory_base.py:39`), so a plain module at the
repository root is enough.

The example below runs gradient *ascent* on the nodes affected by the forget set, then a
short fine-tune on the retain set to recover utility. It exists to show the API surface: replace the body of `__unlearn__` with your own logic.

In [4]:
%%writefile my_method.py
from lethe.unlearners.graph_unlearners.GraphUnlearner import GraphUnlearner
from lethe.core.factory_base import get_instance_kvargs


class MyUnlearner(GraphUnlearner):

    def init(self):
        super().init()
        self.ascent_epochs = self.local.config['parameters']['ascent_epochs']
        self.repair_epochs = self.local.config['parameters']['repair_epochs']
        self.predictor.optimizer = get_instance_kvargs(
            self.local_config['parameters']['optimizer']['class'],
            {'params': self.predictor.model.parameters(),
             **self.local_config['parameters']['optimizer']['parameters']})

    def __unlearn__(self):
        forget_edges = self.dataset.partitions[self.forget_part]
        affected = self.infected_nodes(forget_edges, self.hops)
        repair_nodes = self.dataset.partitions[self.train_part]

        self.predictor.model.train()

        for epoch in range(self.ascent_epochs):
            self.predictor.optimizer.zero_grad()
            loss = -self.task_loss(node_subset=affected)
            loss.backward()
            self.predictor.optimizer.step()
            self.info(f'MyUnlearner ascent epoch={epoch} loss={loss.item():.4f}')

        for epoch in range(self.repair_epochs):
            self.predictor.optimizer.zero_grad()
            loss = self.task_loss(node_subset=repair_nodes)
            loss.backward()
            self.predictor.optimizer.step()
            self.info(f'MyUnlearner repair epoch={epoch} loss={loss.item():.4f}')

        return self.predictor

    def check_configuration(self):
        super().check_configuration()
        p = self.local.config['parameters']
        p['ascent_epochs'] = p.get('ascent_epochs', 3)
        p['repair_epochs'] = p.get('repair_epochs', 5)
        p['optimizer'] = p.get('optimizer', {'class': 'torch.optim.Adam',
                                             'parameters': {'lr': 0.0001}})

Overwriting my_method.py

Now append it to the config's `unlearners` list and re-run. A new config file is written
rather than editing the demo one, so the original stays reproducible, and results go to a
separate path so the two runs can be compared.

In [5]:
from jsonc_parser.parser import JsoncParser

cfg = JsoncParser.parse_file(CONFIG)

cfg["unlearners"].append({
    "class": "my_method.MyUnlearner",
    "parameters": {
        "ascent_epochs": 3,
        "repair_epochs": 5,
        "optimizer": {"class": "torch.optim.Adam", "parameters": {"lr": 0.0001}}
    }
})

MY_RESULTS = "output/runs/demo/DBLP_GCN_mymethod.json"
for m in cfg["evaluator"]["parameters"]["measures"]:
    if m["class"].endswith("SaveValues"):
        m["parameters"]["path"] = MY_RESULTS

MY_CONFIG = "configs/demo/DBLP_GCN_mymethod.jsonc"
with open(MY_CONFIG, "w") as f:
    json.dump(cfg, f, indent=2)

print("Wrote", MY_CONFIG)
print("Unlearners:", [u.get("class", u) for u in cfg["unlearners"]])

Wrote configs/demo/DBLP_GCN_mymethod.jsonc
Unlearners: [{'compose_idt': 'configs/snippets/u_id.json'}, 'lethe.unlearners.GoldModel.GoldModelGraph', 'lethe.unlearners.graph_unlearners.Finetuning.Finetuning', 'my_method.MyUnlearner']

The Original and Gold models are cached under the same `alias`, so this run only pays for
the unlearning methods themselves.

In [6]:
run_lethe(MY_CONFIG, MY_RESULTS)

summarise(load_results(MY_RESULTS))

2026-09-29 14:09:28 | INFO | 35139 - Creating Global Context for: configs/demo/DBLP_GCN_mymethod.jsonc
2026-09-29 14:09:28 | INFO | 35139 - Setting seeds to: 0
2026-09-29 14:09:28 | INFO | 35139 - REMOVAL TYPE SET AS edge
2026-09-29 14:09:28 | INFO | 35139 - Caching System: True.
2026-09-29 14:09:28 | INFO | 35139 - Instantiating: torch_geometric.datasets.CitationFull
{'root': 'resources/data', 'name': 'DBLP'}
2026-09-29 14:09:28 | INFO | 35139 - Created Configurable: lethe.data.data_sources.TorchGeometricDataSource.TorchGeometricDataSource
2026-09-29 14:09:28 | INFO | 35139 - {'class': 'lethe.data.data_sources.TorchGeometricDataSource.TorchGeometricDataSource', 'parameters': {'datasource': {'class': 'torch_geometric.datasets.CitationFull', 'parameters': {'root': 'resources/data', 'name': 'DBLP'}, 'preprocess': []}}}
2026-09-29 14:09:28 | INFO | 35139 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:09:28 | INFO | 35139 - ['all', 'all_shuffled', '-']
2026-09-29 14:09:28 | INFO | 35139 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:09:28 | INFO | 35139 - ['all', 'all_shuffled', '-', 'train_0', 'test']
2026-09-29 14:09:28 | INFO | 35139 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterPercentage
2026-09-29 14:09:28 | INFO | 35139 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train']
2026-09-29 14:09:28 | INFO | 35139 - Instantiating: lethe.data.datasets.DataSplitterGraph.DataSplitterEdgeDifficulty
/path/to/Lethe/lethe/data/datasets/DataSplitterGraph.py:477: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /Users/runner/work/pytorch/pytorch/aten/src/ATen/Context.cpp:823.)
  A_hat = torch.sparse_coo_tensor(edge_index_tilde, weights, (N, N)).coalesce()

2026-09-29 14:09:28 | INFO | 35139 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train', 'forget', 'retain']
2026-09-29 14:09:28 | INFO | 35139 - ['all', 'all_shuffled', '-', 'train_0', 'test', 'validation', 'train', 'forget', 'retain']
2026-09-29 14:09:28 | INFO | 35139 - Created Configurable: lethe.data.datasets.DatasetManager.DatasetManager

2026-09-29 14:09:31 | INFO | 35139 - Loaded Instance from: resources/cached/DBLP_GCN_demo
2026-09-29 14:09:31 | INFO | 35139 - Created Configurable: lethe.model.TorchGraphModel.TorchGraphModel
2026-09-29 14:09:31 | INFO | 35139 - Global Predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x153604530>

2026-09-29 14:09:31 | INFO | 35139 - Created Configurable: lethe.unlearners.composite.Identity

2026-09-29 14:09:32 | INFO | 35139 - Created Configurable: lethe.unlearners.GoldModel.GoldModelGraph

2026-09-29 14:09:33 | INFO | 35139 - Instantiating: torch.optim.Adam
/path/to/Lethe/lethe/unlearners/graph_unlearners/GraphUnlearner.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.labels = torch.tensor(self.labels)
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.unlearners.graph_unlearners.Finetuning.Finetuning

2026-09-29 14:09:33 | INFO | 35139 - Instantiating: torch.optim.Adam
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: my_method.MyUnlearner

2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.running.RunTime
2026-09-29 14:09:33 | INFO | 35139 - Function: <function accuracy_score at 0x30e79c220>
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:09:33 | INFO | 35139 - Function: <function accuracy_score at 0x30e79c220>
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:09:33 | INFO | 35139 - Function: <function accuracy_score at 0x30e79c220>
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.measures.TorchSKLearnGraph
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.LinkTeller.LinkTeller.LinkTeller
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.link_stealing_attack.link_stealing_attack_0.LinkStealing0
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.measures.SaveValues
2026-09-29 14:09:33 | INFO | 35139 - Created Configurable: lethe.evaluations.manager.Evaluator
2026-09-29 14:09:33 | INFO | 35139 - ####		 Evaluating Unlearner Identity 		####

2026-09-29 14:09:34 | INFO | 35139 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x30e7db920>

2026-09-29 14:09:34 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8250564334085779 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32d83a2a0>
2026-09-29 14:09:34 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.811346276257161 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32d83a2a0>
2026-09-29 14:09:34 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32ddb3e60>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(12623, 13781), (1326, 8484), (15922, 16753), (9938, 13268), (11732, 15617)]
2026-09-29 14:09:34 | INFO | 35139 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0053, std=0.0157, min=0.0000, max=0.1223
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0009, min=0.0000, max=0.0096
[ROC Thresholds] Sample thresholds: [       inf 0.12230431 0.03278255 0.03209808 0.00970293]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.052 0.056 0.148]
auc = 0.406166
2026-09-29 14:09:41 | INFO | 35139 - LinkTeller unlearn auc with sampler balanced: 0.406166

Attack 0 target posterior similarity
2026-09-29 14:09:41 | INFO | 35139 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8700928967280654

Attack 0 target posterior similarity
2026-09-29 14:09:42 | INFO | 35139 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7327600672176672
2026-09-29 14:09:42 | INFO | 35139 - ####		 Evaluating Unlearner GoldModelGraph 		####
2026-09-29 14:09:42 | INFO | 35139 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x31751dca0>
Hello, i am unlearning gm at time  time.struct_time(tm_year=2026, tm_mon=9, tm_mday=29, tm_hour=14, tm_min=9, tm_sec=42, tm_wday=1, tm_yday=272, tm_isdst=1)
2026-09-29 14:09:42 | INFO | 35139 - Instantiating: lethe.model.graphs.GCN.GCN
2026-09-29 14:09:42 | INFO | 35139 - [DBG] model cfg: epochs=100 | hidden=[64] | out=?
2026-09-29 14:09:42 | INFO | 35139 - Instantiating: torch.optim.Adam
2026-09-29 14:09:42 | INFO | 35139 - Instantiating: torch.nn.CrossEntropyLoss
2026-09-29 14:09:42 | INFO | 35139 - [DBG] graph: nodes=17716, edges=100448 | train_len=12755 | test_len=3544 | training_set='retain'
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 0 ---> train_loss = 1.3984	 val_loss = 1.3869	 train_acc = 0.1643
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 1 ---> train_loss = 1.3861	 val_loss = 1.3758	 train_acc = 0.2457
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 2 ---> train_loss = 1.3752	 val_loss = 1.3649	 train_acc = 0.3476

2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 3 ---> train_loss = 1.3635	 val_loss = 1.3542	 train_acc = 0.4663
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 4 ---> train_loss = 1.3514	 val_loss = 1.3437	 train_acc = 0.5598
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 5 ---> train_loss = 1.3421	 val_loss = 1.3332	 train_acc = 0.6146
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 6 ---> train_loss = 1.3307	 val_loss = 1.3228	 train_acc = 0.6459
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 7 ---> train_loss = 1.3194	 val_loss = 1.3123	 train_acc = 0.6714
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 8 ---> train_loss = 1.3088	 val_loss = 1.3018	 train_acc = 0.6828
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 9 ---> train_loss = 1.2983	 val_loss = 1.2911	 train_acc = 0.6953
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 10 ---> train_loss = 1.2863	 val_loss = 1.2804	 train_acc = 0.6971
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 11 ---> train_loss = 1.2756	 val_loss = 1.2695	 train_acc = 0.7038

2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 12 ---> train_loss = 1.2648	 val_loss = 1.2586	 train_acc = 0.7086
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 13 ---> train_loss = 1.2537	 val_loss = 1.2475	 train_acc = 0.7141
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 14 ---> train_loss = 1.2420	 val_loss = 1.2363	 train_acc = 0.7167
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 15 ---> train_loss = 1.2306	 val_loss = 1.2251	 train_acc = 0.7189
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 16 ---> train_loss = 1.2183	 val_loss = 1.2138	 train_acc = 0.7207
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 17 ---> train_loss = 1.2068	 val_loss = 1.2024	 train_acc = 0.7192
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 18 ---> train_loss = 1.1956	 val_loss = 1.1910	 train_acc = 0.7232
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 19 ---> train_loss = 1.1835	 val_loss = 1.1795	 train_acc = 0.7229
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 20 ---> train_loss = 1.1706	 val_loss = 1.1680	 train_acc = 0.7296
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 21 ---> train_loss = 1.1601	 val_loss = 1.1566	 train_acc = 0.7253

2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 22 ---> train_loss = 1.1471	 val_loss = 1.1451	 train_acc = 0.7252
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 23 ---> train_loss = 1.1358	 val_loss = 1.1337	 train_acc = 0.7305
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 24 ---> train_loss = 1.1245	 val_loss = 1.1223	 train_acc = 0.7301
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 25 ---> train_loss = 1.1107	 val_loss = 1.1109	 train_acc = 0.7344
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:42 | INFO | 35139 - epoch = 26 ---> train_loss = 1.1008	 val_loss = 1.0996	 train_acc = 0.7327
2026-09-29 14:09:42 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 27 ---> train_loss = 1.0893	 val_loss = 1.0884	 train_acc = 0.7354
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 28 ---> train_loss = 1.0766	 val_loss = 1.0772	 train_acc = 0.7366
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 29 ---> train_loss = 1.0651	 val_loss = 1.0661	 train_acc = 0.7399
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 30 ---> train_loss = 1.0516	 val_loss = 1.0551	 train_acc = 0.7433
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 31 ---> train_loss = 1.0418	 val_loss = 1.0441	 train_acc = 0.7433

2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 32 ---> train_loss = 1.0314	 val_loss = 1.0333	 train_acc = 0.7460
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 33 ---> train_loss = 1.0187	 val_loss = 1.0226	 train_acc = 0.7485
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 34 ---> train_loss = 1.0086	 val_loss = 1.0119	 train_acc = 0.7521
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 35 ---> train_loss = 0.9956	 val_loss = 1.0014	 train_acc = 0.7541
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 36 ---> train_loss = 0.9871	 val_loss = 0.9910	 train_acc = 0.7533
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 37 ---> train_loss = 0.9759	 val_loss = 0.9808	 train_acc = 0.7585
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 38 ---> train_loss = 0.9647	 val_loss = 0.9706	 train_acc = 0.7598
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 39 ---> train_loss = 0.9542	 val_loss = 0.9606	 train_acc = 0.7615
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 40 ---> train_loss = 0.9434	 val_loss = 0.9507	 train_acc = 0.7643
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 41 ---> train_loss = 0.9343	 val_loss = 0.9410	 train_acc = 0.7628

2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 42 ---> train_loss = 0.9230	 val_loss = 0.9314	 train_acc = 0.7651
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 43 ---> train_loss = 0.9143	 val_loss = 0.9220	 train_acc = 0.7686
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 44 ---> train_loss = 0.9034	 val_loss = 0.9128	 train_acc = 0.7707
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 45 ---> train_loss = 0.8934	 val_loss = 0.9037	 train_acc = 0.7761
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 46 ---> train_loss = 0.8865	 val_loss = 0.8947	 train_acc = 0.7762
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 47 ---> train_loss = 0.8762	 val_loss = 0.8859	 train_acc = 0.7773
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 48 ---> train_loss = 0.8675	 val_loss = 0.8773	 train_acc = 0.7783
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 49 ---> train_loss = 0.8562	 val_loss = 0.8688	 train_acc = 0.7816
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 50 ---> train_loss = 0.8492	 val_loss = 0.8605	 train_acc = 0.7825

2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 51 ---> train_loss = 0.8403	 val_loss = 0.8523	 train_acc = 0.7827
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 52 ---> train_loss = 0.8303	 val_loss = 0.8443	 train_acc = 0.7889
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 53 ---> train_loss = 0.8237	 val_loss = 0.8365	 train_acc = 0.7904
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 54 ---> train_loss = 0.8157	 val_loss = 0.8288	 train_acc = 0.7905
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 55 ---> train_loss = 0.8056	 val_loss = 0.8212	 train_acc = 0.7867
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 56 ---> train_loss = 0.8005	 val_loss = 0.8139	 train_acc = 0.7921
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 57 ---> train_loss = 0.7938	 val_loss = 0.8066	 train_acc = 0.7931
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 58 ---> train_loss = 0.7835	 val_loss = 0.7996	 train_acc = 0.7964
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 59 ---> train_loss = 0.7782	 val_loss = 0.7926	 train_acc = 0.7945
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:43 | INFO | 35139 - epoch = 60 ---> train_loss = 0.7674	 val_loss = 0.7858	 train_acc = 0.7973
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 61 ---> train_loss = 0.7640	 val_loss = 0.7792	 train_acc = 0.7989
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 62 ---> train_loss = 0.7582	 val_loss = 0.7727	 train_acc = 0.7999
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 63 ---> train_loss = 0.7488	 val_loss = 0.7663	 train_acc = 0.8002
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 64 ---> train_loss = 0.7420	 val_loss = 0.7601	 train_acc = 0.8045
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 65 ---> train_loss = 0.7362	 val_loss = 0.7540	 train_acc = 0.8058
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 66 ---> train_loss = 0.7285	 val_loss = 0.7481	 train_acc = 0.8078
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 67 ---> train_loss = 0.7235	 val_loss = 0.7423	 train_acc = 0.8089
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 68 ---> train_loss = 0.7174	 val_loss = 0.7366	 train_acc = 0.8100
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 69 ---> train_loss = 0.7113	 val_loss = 0.7310	 train_acc = 0.8099
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:43 | INFO | 35139 - epoch = 70 ---> train_loss = 0.7052	 val_loss = 0.7256	 train_acc = 0.8134
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 71 ---> train_loss = 0.6989	 val_loss = 0.7203	 train_acc = 0.8122
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 72 ---> train_loss = 0.6935	 val_loss = 0.7151	 train_acc = 0.8139
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 73 ---> train_loss = 0.6873	 val_loss = 0.7101	 train_acc = 0.8170
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:43 | INFO | 35139 - epoch = 74 ---> train_loss = 0.6846	 val_loss = 0.7051	 train_acc = 0.8137
2026-09-29 14:09:43 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 75 ---> train_loss = 0.6787	 val_loss = 0.7003	 train_acc = 0.8168
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 76 ---> train_loss = 0.6717	 val_loss = 0.6956	 train_acc = 0.8189
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 77 ---> train_loss = 0.6705	 val_loss = 0.6910	 train_acc = 0.8204
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 78 ---> train_loss = 0.6638	 val_loss = 0.6865	 train_acc = 0.8183
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 79 ---> train_loss = 0.6591	 val_loss = 0.6821	 train_acc = 0.8217
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:44 | INFO | 35139 - epoch = 80 ---> train_loss = 0.6553	 val_loss = 0.6778	 train_acc = 0.8229
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 81 ---> train_loss = 0.6481	 val_loss = 0.6736	 train_acc = 0.8240
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 82 ---> train_loss = 0.6465	 val_loss = 0.6694	 train_acc = 0.8245
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 83 ---> train_loss = 0.6428	 val_loss = 0.6654	 train_acc = 0.8247
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 84 ---> train_loss = 0.6355	 val_loss = 0.6615	 train_acc = 0.8289
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 85 ---> train_loss = 0.6299	 val_loss = 0.6577	 train_acc = 0.8300
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 86 ---> train_loss = 0.6278	 val_loss = 0.6539	 train_acc = 0.8307
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 87 ---> train_loss = 0.6250	 val_loss = 0.6503	 train_acc = 0.8286
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 88 ---> train_loss = 0.6207	 val_loss = 0.6467	 train_acc = 0.8319
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 89 ---> train_loss = 0.6173	 val_loss = 0.6432	 train_acc = 0.8300

2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 90 ---> train_loss = 0.6161	 val_loss = 0.6398	 train_acc = 0.8343
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 91 ---> train_loss = 0.6125	 val_loss = 0.6365	 train_acc = 0.8310
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 92 ---> train_loss = 0.6080	 val_loss = 0.6333	 train_acc = 0.8318
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 93 ---> train_loss = 0.6031	 val_loss = 0.6301	 train_acc = 0.8315
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 94 ---> train_loss = 0.5984	 val_loss = 0.6270	 train_acc = 0.8350
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 95 ---> train_loss = 0.5949	 val_loss = 0.6240	 train_acc = 0.8350
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 96 ---> train_loss = 0.5912	 val_loss = 0.6210	 train_acc = 0.8382
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 97 ---> train_loss = 0.5896	 val_loss = 0.6181	 train_acc = 0.8372
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu
2026-09-29 14:09:44 | INFO | 35139 - epoch = 98 ---> train_loss = 0.5857	 val_loss = 0.6153	 train_acc = 0.8389
2026-09-29 14:09:44 | INFO | 35139 - [DBG] devices: model=mps:0 | x=cpu | ei=cpu | y=cpu

2026-09-29 14:09:44 | INFO | 35139 - epoch = 99 ---> train_loss = 0.5848	 val_loss = 0.6125	 train_acc = 0.8373
2026-09-29 14:09:44 | INFO | 35139 - TorchGraphModel trained on mps in: 2.184216022491455 secs
2026-09-29 14:09:44 | INFO | 35139 - Created Configurable: lethe.model.TorchGraphModel.TorchGraphModel

Done at  time.struct_time(tm_year=2026, tm_mon=9, tm_mday=29, tm_hour=14, tm_min=9, tm_sec=44, tm_wday=1, tm_yday=272, tm_isdst=1)
2026-09-29 14:09:45 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8259029345372461 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32dddafc0>
2026-09-29 14:09:45 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.8150063653723743 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32dddafc0>
2026-09-29 14:09:45 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32db13cb0>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(6805, 15687), (5830, 8065), (5220, 12561), (13618, 17432), (15091, 17401)]
2026-09-29 14:09:45 | INFO | 35139 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0049, std=0.0167, min=0.0000, max=0.1940
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0007, min=0.0000, max=0.0057
[ROC Thresholds] Sample thresholds: [       inf 0.19404516 0.01567953 0.01554299 0.01416786]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.088 0.092 0.098]
auc = 0.403836
2026-09-29 14:09:52 | INFO | 35139 - LinkTeller unlearn auc with sampler balanced: 0.403836

Attack 0 target posterior similarity
2026-09-29 14:09:53 | INFO | 35139 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8707114496719958

Attack 0 target posterior similarity
2026-09-29 14:09:53 | INFO | 35139 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7343838965598843
2026-09-29 14:09:53 | INFO | 35139 - ####		 Evaluating Unlearner Finetuning 		####
2026-09-29 14:09:53 | INFO | 35139 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x31751f200>
2026-09-29 14:09:53 | INFO | 35139 - Starting Finetuning with 1 epochs
2026-09-29 14:09:53 | INFO | 35139 - Finetuning - epoch = 0 ---> var_loss = 0.6255

2026-09-29 14:09:53 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8253386004514672 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32ddb04d0>
2026-09-29 14:09:53 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.8128580521960534 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32ddb04d0>
2026-09-29 14:09:53 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x3311fffb0>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(6805, 15687), (5830, 8065), (5220, 12561), (13618, 17432), (15091, 17401)]
2026-09-29 14:09:53 | INFO | 35139 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0048, std=0.0168, min=0.0000, max=0.1965
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0008, min=0.0000, max=0.0065
[ROC Thresholds] Sample thresholds: [       inf 0.19652298 0.00753946 0.00652936 0.00630796]
[ROC] FPR: [0.    0.    0.    0.002 0.002], TPR: [0.    0.002 0.118 0.118 0.12 ]
auc = 0.404138
2026-09-29 14:10:00 | INFO | 35139 - LinkTeller unlearn auc with sampler balanced: 0.404138

Attack 0 target posterior similarity
2026-09-29 14:10:01 | INFO | 35139 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8709738428955316

Attack 0 target posterior similarity
2026-09-29 14:10:01 | INFO | 35139 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7335296120992087
2026-09-29 14:10:01 | INFO | 35139 - ####		 Evaluating Unlearner MyUnlearner 		####
2026-09-29 14:10:01 | INFO | 35139 - Unlearning copied predictor: <lethe.model.TorchGraphModel.TorchGraphModel object at 0x3175305c0>
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner ascent epoch=0 loss=-0.6217
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner ascent epoch=1 loss=-0.6220
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner ascent epoch=2 loss=-0.6247
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner repair epoch=0 loss=0.5893
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner repair epoch=1 loss=0.5897
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner repair epoch=2 loss=0.5878
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner repair epoch=3 loss=0.5881
2026-09-29 14:10:01 | INFO | 35139 - MyUnlearner repair epoch=4 loss=0.5885

2026-09-29 14:10:01 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: unlearned, unlearned graph: True: 0.8259029345372461 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32ddda5a0>
2026-09-29 14:10:01 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "forget", target model: unlearned, unlearned graph: True: 0.8101527689369828 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x32ddda5a0>
2026-09-29 14:10:01 | INFO | 35139 - sklearn.metrics.accuracy_score on partition: "test", target model: original, unlearned graph: False: 0.8244920993227991 of <lethe.model.TorchGraphModel.TorchGraphModel object at 0x31751c170>
[Edge Sampling] #Exist: 2643 | #Non-Exist: 2643
[Sample Exist] [(35, 38), (35, 462), (35, 39), (35, 3034), (38, 39)]
[Sample Non-Exist] [(6805, 15687), (5830, 8065), (5220, 12561), (13618, 17432), (15091, 17401)]
2026-09-29 14:10:01 | INFO | 35139 - LinkTeller: capped to 500 edges for evaluation

[Norm Stats] Exist Edges: mean=0.0047, std=0.0168, min=0.0000, max=0.1971
[Norm Stats] Non-Exist Edges: mean=0.0005, std=0.0008, min=0.0000, max=0.0060
[ROC Thresholds] Sample thresholds: [       inf 0.19711752 0.00756298 0.006664   0.00644723]
[ROC] FPR: [0. 0. 0. 0. 0.], TPR: [0.    0.002 0.12  0.124 0.126]
auc = 0.39020600000000005
2026-09-29 14:10:08 | INFO | 35139 - LinkTeller unlearn auc with sampler balanced: 0.39020600000000005

Attack 0 target posterior similarity
2026-09-29 14:10:09 | INFO | 35139 - Link Stealing Attack unlearned 0 exist/non_exist: 0.8696319452095934

Attack 0 target posterior similarity
2026-09-29 14:10:09 | INFO | 35139 - Link Stealing Attack 0 unlearned forget/non_exist: 0.7322058961355424

           Method  RunTime     Acc  Acc(forget)  LT AUC  LS AUC
0        Identity   0.3425  0.8251       0.8113  0.4062  0.7328
1  GoldModelGraph   3.3311  0.8259       0.8150  0.4038  0.7344
2      Finetuning   0.3767  0.8253       0.8129  0.4041  0.7335
3     MyUnlearner   0.4453  0.8259       0.8102  0.3902  0.7322

## 4. Where to go next

See the README for the full configuration reference.